services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: lap-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - lap-network

  nginx:
    image: nginx:1.25-alpine
    platform: linux/arm64
    container_name: lap-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - lap-network

networks:
  lap-network:
    driver: bridge 